env:
  node: true
  commonjs: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 13
rules:
  no-console: "warn"
  consistent-return: "warn"
  no-trailing-spaces: "warn"
  no-whitespace-before-property: "warn"
  no-multiple-empty-lines: ["warn", { max: 1 }]
