const { Counter, Gauge } = require('prom-client');
const { injectMetrics, LiveKitPrometheusAgent } = require('./index.js');

const SFULK_NAMES = {
  API_ERRORS: 'sfu_livekit_errors_total',
  EGRESS_ERRORS: 'sfu_livekit_egress_errors_total',
  RECORDING_ERRORS: 'sfu_livekit_recording_errors_total' ,
  RECORDER_STATUS: 'sfu_livekit_recorder_status',
  RECORDER_RESTARTS: 'sfu_livekit_recorder_restarts_total',
  RECORDER_OUT_REQUESTS: 'sfu_livekit_recorder_out_requests_total',
  RECORDER_IN_REQUESTS: 'sfu_livekit_recorder_in_requests_total',
  RECORDER_RETRIES: 'sfu_livekit_recorder_retries_total',
  RECORDER_RETRY_FAILURES: 'sfu_livekit_recorder_retry_failures_total',
  RECORDER_START_EVENTS: 'sfu_livekit_recorder_start_events_total',
  RECORDER_STOP_EVENTS: 'sfu_livekit_recorder_stop_events_total',
  RECORDER_ACTIVE_RECORDINGS: 'sfu_livekit_recorder_active_recordings',
  RECORDER_PENDING_RETRY_TIMEOUTS: 'sfu_livekit_recorder_pending_retry_timeouts',
  HOOKS_MISSING_ATTRIBUTE: 'sfu_livekit_hooks_missing_attribute',
  ACTIVE_AGENTS: 'sfu_livekit_active_agents_total',
}

let LIVEKIT_METRICS;
const buildDefaultMetrics = () => {
  if (LIVEKIT_METRICS == null) {
    LIVEKIT_METRICS = {
      [SFULK_NAMES.API_ERRORS]: new Counter({
        name: SFULK_NAMES.API_ERRORS,
        help: 'Total number of LiveKIT API call failures',
        labelNames: ['errorMessage'],
      }),

      [SFULK_NAMES.EGRESS_ERRORS]: new Counter({
        name: SFULK_NAMES.EGRESS_ERRORS,
        help: 'Total number of egress API errors',
        labelNames: ['errorMessage'],
      }),

      [SFULK_NAMES.RECORDER_STATUS]: new Gauge({
        name: SFULK_NAMES.RECORDER_STATUS,
        help: 'Status of bbb-webrtc-recorder (livekit module)',
      }),

      [SFULK_NAMES.RECORDER_RESTARTS]: new Counter({
        name: SFULK_NAMES.RECORDER_RESTARTS,
        help: 'Total restarts of bbb-webrtc-recorder (livekit module)',
      }),

      [SFULK_NAMES.RECORDING_ERRORS]: new Counter({
        name: SFULK_NAMES.RECORDING_ERRORS,
        help: 'Total recording errors generated by the livekit module',
        labelNames: ['error'],
      }),

      [SFULK_NAMES.RECORDER_OUT_REQUESTS]: new Counter({
        name: SFULK_NAMES.RECORDER_OUT_REQUESTS,
        help: 'Total number of outgoing requests to bbb-webrtc-recorder (livekit module)',
        labelNames: ['method'],
      }),

      [SFULK_NAMES.RECORDER_IN_REQUESTS]: new Counter({
        name: SFULK_NAMES.RECORDER_IN_REQUESTS,
        help: 'Total number of incoming requests to bbb-webrtc-recorder (livekit module)',
        labelNames: ['method'],
      }),

      [SFULK_NAMES.RECORDER_RETRIES]: new Counter({
        name: SFULK_NAMES.RECORDER_RETRIES,
        help: 'Total number of recording start retries scheduled',
      }),

      [SFULK_NAMES.RECORDER_RETRY_FAILURES]: new Counter({
        name: SFULK_NAMES.RECORDER_RETRY_FAILURES,
        help: 'Total number of recording start retries that failed (reached max attempts)',
        labelNames: ['error'],
      }),

      [SFULK_NAMES.RECORDER_START_EVENTS]: new Counter({
        name: SFULK_NAMES.RECORDER_START_EVENTS,
        help: 'Total number of recording start events sent to BBB',
        labelNames: ['source'],
      }),

      [SFULK_NAMES.RECORDER_STOP_EVENTS]: new Counter({
        name: SFULK_NAMES.RECORDER_STOP_EVENTS,
        help: 'Total number of recording stop events sent to BBB',
        labelNames: ['source'],
      }),

      [SFULK_NAMES.RECORDER_ACTIVE_RECORDINGS]: new Gauge({
        name: SFULK_NAMES.RECORDER_ACTIVE_RECORDINGS,
        help: 'Number of currently active recordings being managed',
      }),

      [SFULK_NAMES.RECORDER_PENDING_RETRY_TIMEOUTS]: new Gauge({
        name: SFULK_NAMES.RECORDER_PENDING_RETRY_TIMEOUTS,
        help: 'Number of recording retry timeouts currently pending',
      }),

      [SFULK_NAMES.HOOKS_MISSING_ATTRIBUTE]: new Counter({
        name: SFULK_NAMES.HOOKS_MISSING_ATTRIBUTE,
        help: 'Total number of webhook events missing expected attributes',
        labelNames: ['attribute'],
      }),

      [SFULK_NAMES.ACTIVE_AGENTS]: new Gauge({
        name: SFULK_NAMES.ACTIVE_AGENTS,
        help: 'Number of active LiveKit RTC agents created by bbb-webrtc-sfu',
      }),
    }
  }

  return LIVEKIT_METRICS;
};

injectMetrics(buildDefaultMetrics());

module.exports = {
  SFULK_NAMES,
  LIVEKIT_METRICS,
  PrometheusAgent: LiveKitPrometheusAgent,
};
