const { Counter, Gauge } = require('prom-client');
const { injectMetrics, LiveKitPrometheusAgent } = require('./index.js');

const SFULK_NAMES = {
  API_ERRORS: 'sfu_livekit_errors_total',
  EGRESS_ERRORS: 'sfu_livekit_egress_errors_total',
  RECORDING_ERRORS: 'sfu_livekit_recording_errors_total' ,
  RECORDER_STATUS: 'sfu_livekit_recorder_status',
  RECORDER_RESTARTS: 'sfu_livekit_recorder_restarts_total',
}

let LIVEKIT_METRICS;
const buildDefaultMetrics = () => {
  if (LIVEKIT_METRICS == null) {
    LIVEKIT_METRICS = {
      [SFULK_NAMES.API_ERRORS]: new Counter({
        name: SFULK_NAMES.API_ERRORS,
        help: 'Total number of LiveKIT API call failures',
        labelNames: ['errorMessage'],
      }),

      [SFULK_NAMES.EGRESS_ERRORS]: new Counter({
        name: SFULK_NAMES.EGRESS_ERRORS,
        help: 'Total number of egress API errors',
        labelNames: ['errorMessage'],
      }),

      [SFULK_NAMES.RECORDER_STATUS]: new Gauge({
        name: SFULK_NAMES.RECORDER_STATUS,
        help: 'Status of bbb-webrtc-recorder (livekit module)',
      }),

      [SFULK_NAMES.RECORDER_RESTARTS]: new Counter({
        name: SFULK_NAMES.RECORDER_RESTARTS,
        help: 'Total restarts of bbb-webrtc-recorder (livekit module)',
      }),

      [SFULK_NAMES.RECORDING_ERRORS]: new Counter({
        name: SFULK_NAMES.RECORDING_ERRORS,
        help: 'Total recording errors generated by the livekit module',
        labelNames: ['error'],
      }),
    }
  }

  return LIVEKIT_METRICS;
};

injectMetrics(buildDefaultMetrics());

module.exports = {
  SFULK_NAMES,
  LIVEKIT_METRICS,
  PrometheusAgent: LiveKitPrometheusAgent,
};
