const { Counter, Gauge, Histogram } = require('prom-client');
const { injectMetrics, LiveKitPrometheusAgent } = require('./index.js');

const SFULK_NAMES = {
  API_ERRORS: 'sfu_livekit_errors_total',
  EGRESS_ERRORS: 'sfu_livekit_egress_errors_total',
  RECORDING_ERRORS: 'sfu_livekit_recording_errors_total' ,
  RECORDER_STATUS: 'sfu_livekit_recorder_status',
  RECORDER_RESTARTS: 'sfu_livekit_recorder_restarts_total',
  RECORDER_OUT_REQUESTS: 'sfu_livekit_recorder_out_requests_total',
  RECORDER_IN_REQUESTS: 'sfu_livekit_recorder_in_requests_total',
  RECORDER_RETRIES: 'sfu_livekit_recorder_retries_total',
  RECORDER_RETRY_FAILURES: 'sfu_livekit_recorder_retry_failures_total',
  RECORDER_START_EVENTS: 'sfu_livekit_recorder_start_events_total',
  RECORDER_STOP_EVENTS: 'sfu_livekit_recorder_stop_events_total',
  RECORDER_ACTIVE_RECORDINGS: 'sfu_livekit_recorder_active_recordings',
  RECORDER_PENDING_RETRY_TIMEOUTS: 'sfu_livekit_recorder_pending_retry_timeouts',
  RECORDER_ORPHANED_RECORDINGS: 'sfu_livekit_recorder_orphaned_recordings',
  RECORDER_RESYNCED_RECORDINGS: 'sfu_livekit_recorder_resynced_recordings_total',
  RECORDER_LOST_RECORDINGS: 'sfu_livekit_recorder_lost_recordings_total',
  HOOKS_MISSING_ATTRIBUTE: 'sfu_livekit_hooks_missing_attribute',
  ACTIVE_AGENTS: 'sfu_livekit_active_agents_total',
  ACTIVE_RTC_EVT_RCVRS: 'sfu_livekit_active_rtc_event_receivers_total',
  RTC_EVT_RCVRS_DISCONNECTED: 'sfu_livekit_rtc_event_receivers_disconnected_total',
  RTC_EVT_RCVRS_RECONNECTING: 'sfu_livekit_rtc_event_receivers_reconnecting_total',
  RTC_EVT_RCVRS_RECONNECTED: 'sfu_livekit_rtc_event_receivers_reconnected_total',
  RTC_EVT_RCVRS_CONNECTION_RETRIES: 'sfu_livekit_rtc_event_receivers_connection_retries_total',
  RTC_EVT_RCVRS_CONNECTION_RETRY_FAILURES: 'sfu_livekit_rtc_event_receivers_connection_retry_failures_total',
  RTC_EVT_RCVRS_PENDING_RETRY_TIMEOUTS: 'sfu_livekit_rtc_event_receivers_pending_retry_timeouts',
  RTC_EVT_EMITTED: 'sfu_livekit_rtc_events_emitted_total',
  TRACK_PUBLISH_FAILURES: 'sfu_livekit_track_publish_failures_total',
  TOKEN_GEN_ERRORS: 'sfu_livekit_token_generation_errors_total',
  TIME_TO_MUTE: 'sfu_livekit_time_to_mute',
  TIME_TO_UNMUTE: 'sfu_livekit_time_to_unmute',
  EXTERNAL_CAPTURE_STATUS_CHANGES: 'sfu_livekit_external_capture_status_changes_total',
  EXTERNAL_EVENT_CAPTURES: 'sfu_livekit_external_event_captures',
}

let LIVEKIT_METRICS;
const buildDefaultMetrics = () => {
  if (LIVEKIT_METRICS == null) {
    LIVEKIT_METRICS = {
      [SFULK_NAMES.API_ERRORS]: new Counter({
        name: SFULK_NAMES.API_ERRORS,
        help: 'Total number of LiveKIT API call failures',
        labelNames: ['errorMessage'],
      }),

      [SFULK_NAMES.EGRESS_ERRORS]: new Counter({
        name: SFULK_NAMES.EGRESS_ERRORS,
        help: 'Total number of egress API errors',
        labelNames: ['errorMessage'],
      }),

      [SFULK_NAMES.RECORDER_STATUS]: new Gauge({
        name: SFULK_NAMES.RECORDER_STATUS,
        help: 'Status of bbb-webrtc-recorder (livekit module)',
      }),

      [SFULK_NAMES.RECORDER_RESTARTS]: new Counter({
        name: SFULK_NAMES.RECORDER_RESTARTS,
        help: 'Total restarts of bbb-webrtc-recorder (livekit module)',
      }),

      [SFULK_NAMES.RECORDING_ERRORS]: new Counter({
        name: SFULK_NAMES.RECORDING_ERRORS,
        help: 'Total recording errors generated by the livekit module',
        labelNames: ['error'],
      }),

      [SFULK_NAMES.RECORDER_OUT_REQUESTS]: new Counter({
        name: SFULK_NAMES.RECORDER_OUT_REQUESTS,
        help: 'Total number of outgoing requests to bbb-webrtc-recorder (livekit module)',
        labelNames: ['method'],
      }),

      [SFULK_NAMES.RECORDER_IN_REQUESTS]: new Counter({
        name: SFULK_NAMES.RECORDER_IN_REQUESTS,
        help: 'Total number of incoming requests to bbb-webrtc-recorder (livekit module)',
        labelNames: ['method'],
      }),

      [SFULK_NAMES.RECORDER_RETRIES]: new Counter({
        name: SFULK_NAMES.RECORDER_RETRIES,
        help: 'Total number of recording start retries scheduled',
      }),

      [SFULK_NAMES.RECORDER_RETRY_FAILURES]: new Counter({
        name: SFULK_NAMES.RECORDER_RETRY_FAILURES,
        help: 'Total number of recording start retries that failed (reached max attempts)',
        labelNames: ['error'],
      }),

      [SFULK_NAMES.RECORDER_START_EVENTS]: new Counter({
        name: SFULK_NAMES.RECORDER_START_EVENTS,
        help: 'Total number of recording start events sent to BBB',
        labelNames: ['source'],
      }),

      [SFULK_NAMES.RECORDER_STOP_EVENTS]: new Counter({
        name: SFULK_NAMES.RECORDER_STOP_EVENTS,
        help: 'Total number of recording stop events sent to BBB',
        labelNames: ['source'],
      }),

      [SFULK_NAMES.RECORDER_ACTIVE_RECORDINGS]: new Gauge({
        name: SFULK_NAMES.RECORDER_ACTIVE_RECORDINGS,
        help: 'Number of currently active recordings being managed',
      }),

      [SFULK_NAMES.RECORDER_PENDING_RETRY_TIMEOUTS]: new Gauge({
        name: SFULK_NAMES.RECORDER_PENDING_RETRY_TIMEOUTS,
        help: 'Number of recording retry timeouts currently pending',
      }),

      [SFULK_NAMES.RECORDER_ORPHANED_RECORDINGS]: new Gauge({
        name: SFULK_NAMES.RECORDER_ORPHANED_RECORDINGS,
        help: 'Number of recordings currently in orphaned state (waiting for recorder reconnection)',
      }),

      [SFULK_NAMES.RECORDER_RESYNCED_RECORDINGS]: new Counter({
        name: SFULK_NAMES.RECORDER_RESYNCED_RECORDINGS,
        help: 'Total number of recordings successfully resynced after recorder reconnection',
      }),

      [SFULK_NAMES.RECORDER_LOST_RECORDINGS]: new Counter({
        name: SFULK_NAMES.RECORDER_LOST_RECORDINGS,
        help: 'Total number of recordings confirmed lost after recorder crash',
      }),

      [SFULK_NAMES.HOOKS_MISSING_ATTRIBUTE]: new Counter({
        name: SFULK_NAMES.HOOKS_MISSING_ATTRIBUTE,
        help: 'Total number of webhook events missing expected attributes',
        labelNames: ['attribute'],
      }),

      [SFULK_NAMES.ACTIVE_AGENTS]: new Gauge({
        name: SFULK_NAMES.ACTIVE_AGENTS,
        help: 'Number of active LiveKit RTC agents created by bbb-webrtc-sfu',
      }),

      [SFULK_NAMES.ACTIVE_RTC_EVT_RCVRS]: new Gauge({
        name: SFULK_NAMES.ACTIVE_RTC_EVT_RCVRS,
        help: 'Number of active LiveKit RTC event receivers created by bbb-webrtc-sfu',
      }),

      [SFULK_NAMES.RTC_EVT_RCVRS_DISCONNECTED]: new Counter({
        name: SFULK_NAMES.RTC_EVT_RCVRS_DISCONNECTED,
        help: 'Total number of LiveKit RTC event receivers that have disconnected',
        labelNames: ['disconnectReason'],
      }),

      [SFULK_NAMES.RTC_EVT_RCVRS_RECONNECTING]: new Counter({
        name: SFULK_NAMES.RTC_EVT_RCVRS_RECONNECTING,
        help: 'Total number of LiveKit RTC event receivers that are reconnecting',
      }),

      [SFULK_NAMES.RTC_EVT_RCVRS_RECONNECTED]: new Counter({
        name: SFULK_NAMES.RTC_EVT_RCVRS_RECONNECTED,
        help: 'Total number of LiveKit RTC event receivers that have reconnected',
      }),

      [SFULK_NAMES.RTC_EVT_RCVRS_CONNECTION_RETRIES]: new Counter({
        name: SFULK_NAMES.RTC_EVT_RCVRS_CONNECTION_RETRIES,
        help: 'Total number of connection retry attempts scheduled for RTC event receivers',
      }),

      [SFULK_NAMES.RTC_EVT_RCVRS_CONNECTION_RETRY_FAILURES]: new Counter({
        name: SFULK_NAMES.RTC_EVT_RCVRS_CONNECTION_RETRY_FAILURES,
        help: 'Total number of connection retry attempts that failed (reached max attempts or non-retriable error)',
        labelNames: ['error'],
      }),

      [SFULK_NAMES.RTC_EVT_RCVRS_PENDING_RETRY_TIMEOUTS]: new Gauge({
        name: SFULK_NAMES.RTC_EVT_RCVRS_PENDING_RETRY_TIMEOUTS,
        help: 'Number of pending retry timeouts for RTC event receivers',
      }),

      [SFULK_NAMES.RTC_EVT_EMITTED]: new Counter({
        name: SFULK_NAMES.RTC_EVT_EMITTED,
        help: 'Total number of LiveKit RTC events emitted by event receivers',
        labelNames: ['eventName'],
      }),

      [SFULK_NAMES.TRACK_PUBLISH_FAILURES]: new Counter({
        name: SFULK_NAMES.TRACK_PUBLISH_FAILURES,
        help: 'Total number of track publish failures',
        labelNames: ['error', 'source'],
      }),

      [SFULK_NAMES.TOKEN_GEN_ERRORS]: new Counter({
        name: SFULK_NAMES.TOKEN_GEN_ERRORS,
        help: 'Total number of errors encountered during LiveKit token generation',
        labelNames: ['errorMessage'],
      }),

      [SFULK_NAMES.TIME_TO_MUTE]: new Histogram({
        name: SFULK_NAMES.TIME_TO_MUTE,
        help: 'Time to mute in seconds',
        labelNames: ['operation'],
        buckets: [0.002, 0.005, 0.01, 0.015, 0.02, 0.0375, 0.1, 0.5, 1, 2.5],
      }),

      [SFULK_NAMES.TIME_TO_UNMUTE]: new Histogram({
        name: SFULK_NAMES.TIME_TO_UNMUTE,
        help: 'Time to unmute in seconds',
        labelNames: ['operation'],
        buckets: [0.002, 0.005, 0.01, 0.015, 0.02, 0.0375, 0.1, 0.5, 1, 2.5],
      }),

      [SFULK_NAMES.EXTERNAL_CAPTURE_STATUS_CHANGES]: new Counter({
        name: SFULK_NAMES.EXTERNAL_CAPTURE_STATUS_CHANGES,
        help: 'Total external capture status-change events processed',
        labelNames: ['event', 'enabled'],
      }),

      [SFULK_NAMES.EXTERNAL_EVENT_CAPTURES]: new Gauge({
        name: SFULK_NAMES.EXTERNAL_EVENT_CAPTURES,
        help: 'Number of active recordings attributed solely to an external capture event',
      }),
    }
  }

  return LIVEKIT_METRICS;
};

injectMetrics(buildDefaultMetrics());

module.exports = {
  SFULK_NAMES,
  LIVEKIT_METRICS,
  PrometheusAgent: LiveKitPrometheusAgent,
};
