const { Gauge, Counter, } = require('prom-client');
const { injectMetrics, ScreensharePrometheusAgent } = require('./index.js');

const SFUS_NAMES = {
  SESSIONS: 'sfu_screenshare_sessions',
  REQS: 'sfu_screenshare_reqs_total',
  QUEUED_REQUESTS: 'sfu_screenshare_queued_reqs',
  QUEUE_FAILURES: 'sfu_screenshare_queue_failures_total',
  RECORDER_STATUS: 'sfu_screenshare_recorder_status',
  RECORDER_RESTARTS: 'sfu_screenshare_recorder_restarts_total',
  RECORDING_ERRORS : 'sfu_screenshare_recording_errors_total',
  ERRORS: 'sfu_screenshare_errors_total',
}

let SCREENSHARE_METRICS;
const buildDefaultMetrics = () => {
  if (SCREENSHARE_METRICS == null) {
    SCREENSHARE_METRICS = {
      [SFUS_NAMES.SESSIONS]: new Gauge({
        name: SFUS_NAMES.SESSIONS,
        help: 'Number of active sessions in the screenshare module',
      }),

      [SFUS_NAMES.REQS]: new Counter({
        name: SFUS_NAMES.REQS,
        help: 'Total requisitions received by the screenshare module',
      }),

      [SFUS_NAMES.RECORDER_STATUS]: new Gauge({
        name: SFUS_NAMES.RECORDER_STATUS,
        help: 'Status of bbb-webrtc-recorder (screenshare module)',
      }),

      [SFUS_NAMES.RECORDER_RESTARTS]: new Counter({
        name: SFUS_NAMES.RECORDER_RESTARTS,
        help: 'Total restarts of bbb-webrtc-recorder (screenshare module)',
      }),

      [SFUS_NAMES.RECORDING_ERRORS]: new Counter({
        name: SFUS_NAMES.RECORDING_ERRORS,
        help: 'Total recording errors generated by the screenshare module',
        labelNames: ['error', 'recordingAdapter'],
      }),

      [SFUS_NAMES.ERRORS]: new Counter({
        name: SFUS_NAMES.ERRORS,
        help: 'Total error responses generated by the screenshare module',
        labelNames: ['method', 'errorCode'],
      }),

      [SFUS_NAMES.QUEUED_REQUESTS]: new Gauge({
        name: SFUS_NAMES.QUEUED_REQUESTS,
        help: 'Queued requests in the screenshare module',
      }),

      [SFUS_NAMES.QUEUE_FAILURES]: new Counter({
        name: SFUS_NAMES.QUEUE_FAILURES,
        help: 'Total queue failures in the screenshare module',
        labelNames: ['reason'],
      }),
    }
  }

  return SCREENSHARE_METRICS;
};

injectMetrics(buildDefaultMetrics());

module.exports = {
  SFUS_NAMES,
  SCREENSHARE_METRICS,
  PrometheusAgent: ScreensharePrometheusAgent,
};
